[package]
name = "btknmle-sock"
version = "0.1.0"
authors = ["yskszk63 <yskszk63@gamil.com>"]
edition = "2018"

[dependencies]
tokio = "0.2.0-alpah"
tokio-net = "0.2.0-alpah"
futures-preview = "0.3.0-alpah"
mio = "0.6"
bytes = "0.4"
libc = "0.2"
