FROM debian:buster-slim as builder

ARG RUST_VERSION
ARG RUSTUP_VERSION

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH

RUN set -eux; \
    apt update; \
    apt install -y --no-install-recommends \
        ca-certificates \
        gcc \
        libc6-dev \
        wget \
        ; \
    case $TARGETPLATFORM in \
        linux/amd64 ) RUST_ARCH=x86_64-unknown-linux-gnu ;; \
        linux/arm/v7 ) RUST_ARCH=armv7-unknown-linux-gnueabihf ;; \
        linux/arm/v5 ) RUST_ARCH=arm-unknown-linux-gnueabihf ;; \
    esac ;\
    url="https://static.rust-lang.org/rustup/archive/${RUSTUP_VERSION}/${RUST_ARCH}/rustup-init"; \
    wget "$url"; \
    chmod +x rustup-init; \
    ./rustup-init -y --no-modify-path --profile minimal --default-toolchain $RUST_VERSION; \
    rm rustup-init; \
    chmod -R a+w $RUSTUP_HOME $CARGO_HOME; \
    rustup --version; \
    cargo --version; \
    rustc --version; \
    apt remove -y --auto-remove \
        wget \
        ; \
    rm -rf /var/lib/apt/lists/*;
