[package]
name = "btknmle"
version = "0.1.0"
authors = ["yskszk63 <yskszk63@gamil.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version="0.2", features=["sync", "rt-core", "rt-util", "stream"] }
futures = "0.3"
bytes = "0.5"
either = "1.5"
bitflags = "1.2"
failure = "0.1.6"
input = "0.4"
btknmle-server = { path="../btknmle-server" }
btknmle-input = { path="../btknmle-input" }
btknmle-hid = { path="../btknmle-hid" }
btknmle-keydb = { path="../btknmle-keydb" }
log = "0.4"
env_logger = "0.7"
dotenv = "0.14"

[dev-dependencies]
tokio = { version="0.2", features=["macros"] }
