[package]
name = "btknmle-input"
version = "0.1.0"
authors = ["yskszk63 <yskszk63@gamil.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
input = "0.4"
udev = "0.2"
tokio = { version="0.2", features=["io-driver"] }
futures = "0.3"
bytes = "0.5"
mio = "0.6"
failure = "0.1.6"
libc = "0.2"
log = "0.4"

[dev-dependencies]
dotenv = "0.14"
env_logger = "0.7"

[build-dependencies]
cc = "1.0"
