[package]
name = "btknmle-keydb"
version = "0.1.0"
authors = ["yskszk63 <yskszk63@gamil.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.2.0-alpha"
futures-preview = "0.3.0-alpha"
bytes = "0.4"
failure = "0.1.6"
toml = "0.5"
btknmle-pkt = { path="../btknmle-pkt" }
