[package]
name = "btknmle-server"
version = "0.1.0"
authors = ["yskszk63 <yskszk63@gamil.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.2"
tokio-util = { version="0.2", features=["codec"] }
futures = "0.3"
bytes = "0.5"
either = "1.5"
bitflags = "1.2"
failure = "0.1.6"
btknmle-sock = { path="../btknmle-sock" }
btknmle-pkt = { path="../btknmle-pkt" }
log = "0.4"

[dev-dependencies]
env_logger = "0.7"
dotenv = "0.14"
tokio = { version="0.2", features=["macros", "rt-core"] }
