#!/bin/bash

# workaround
# https://github.com/rust-lang/cargo/issues/7451
cat << EOF | sudo tee /etc/exports
$(pwd) 127.0.0.1/8(rw,sync,no_root_squash,no_subtree_check)
$HOME/.cargo 127.0.0.1/8(rw,sync,no_root_squash,no_subtree_check)
EOF
sudo exportfs -ra
docker volume create --driver local --opt type=nfs --opt o="addr=127.0.0.1,rw" --opt device=":$(pwd)" build
docker volume create --driver local --opt type=nfs --opt o="addr=127.0.0.1,rw" --opt device=":$HOME/.cargo" cargo

# archlinuxarm-rpi
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker build ci/archlinuxarm-rpi -t archlinuxarm-rpi-build

cargo fetch

cp Cargo.toml{,.bak}
# https://github.com/rust-lang/rust/issues/62896
cat << EOF >> Cargo.toml
[profile.release]
codegen-units = 1
EOF
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker run --rm -v build:/build -v cargo:/opt/cargo -u $(id -u):$(id -g) archlinuxarm-rpi-build
mv Cargo.toml{.bak,}

ls -l target/arm-unknown-linux-gnueabihf/release/btknmle
