name: build

on:
  push:
    paths-ignore:
    - 'support/*'
    - '.github/workflows/rustimg.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      RUST_TEST_THREADS: 1
    steps:
    - uses: actions/checkout@v2

    - run: rustup update

    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo bin
      uses: actions/cache@v1
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}

    #- name: Cache cargo build
    #  uses: actions/cache@v1
    #  with:
    #    path: target
    #    key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Install kcov dependencies
      run: sudo apt install -y cmake curl g++ jq python binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev

    - name: Install cargo-kcov
      run: "[ -f ~/.cargo/bin/cargo-kcov ] || cargo install cargo-kcov"

    - name: Install kcov
      run: "[ -f ~/.cargo/bin/kcov] || (cargo kcov --print-install-kcov-sh | sh)"

    - run: sudo apt update && sudo apt install -y libudev-dev libinput-dev

    - name: Check format
      run: cargo fmt -- --check

    - name: Build
      run: cargo build --verbose

    - name: Run kcov
      run: cargo kcov -v --all --no-fail-fast

    - uses: codecov/codecov-action@v1

  build-image:
    runs-on: ubuntu-latest
    needs: check
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        arch:
        - amd64
        - arm32v5
        - arm32v7
    env:
      DOCKER_REPO: yskszk63/btknmle

    steps:
    - uses: actions/checkout@v2

    # work around for `Value too large for defined data type;`
    - name: Setup btrfs volume driver
      run: |
        sudo systemctl stop docker.service
        sudo fallocate -l10GB /mnt/docker.img
        sudo mkfs.btrfs /mnt/docker.img
        sudo mount -t btrfs /mnt/docker.img /var/lib/docker
        echo '{"storage-driver":"btrfs"}' | sudo tee /etc/docker/daemon.json > /dev/null
        sudo systemctl start docker.service

    - name: Setup binfmt
      run: |
        docker run --rm --privileged "$BINFMT_IMAGE"
      env:
        BINFMT_IMAGE: 'docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64'

    - name: Login Doker
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      env:
        DOCKER_USERNAME: yskszk63
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push
      run: |
        case "${{ matrix.arch }}" in
          "amd64")
            TARGETPLATFORM=linux/amd64
            ;;
          "arm32v7")
            TARGETPLATFORM=linux/arm/v7
            ;;
          "arm32v5")
            TARGETPLATFORM=linux/arm/v5
            ;;
        esac
        docker build \
          -t $DOCKER_REPO:$TARGETARCH \
          --build-arg TARGETPLATFORM=${TARGETPLATFORM} \
          .
        docker push $DOCKER_REPO:$TARGETARCH
      env:
        TARGETARCH: ${{ matrix.arch }}

    #- name: Build and push with tag
    #  if: startsWith(github.ref, 'refs/tags/')
    #  run: |
    #    TAG=${GITHUB_REF##*/}
    #    docker buildx build --platform "$PLATFORM" --push -t $DOCKER_REPO:$TAG .

  push-manifest:
    runs-on: ubuntu-latest
    needs: build-image
    if: github.ref == 'refs/heads/master'
    env:
      DOCKER_REPO: yskszk63/btknmle
      DOCKER_CLI_EXPERIMENTAL: enabled

    steps:
    - name: Login Doker
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      env:
        DOCKER_USERNAME: yskszk63
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

    - name: Create manifest
      run: |
        docker manifest create $DOCKER_REPO:latest \
          $DOCKER_REPO:amd64 \
          $DOCKER_REPO:arm32v7 \
          $DOCKER_REPO:arm32v5
        docker manifest annotate --variant v7 $DOCKER_REPO:latest $DOCKER_REPO:arm32v7
        docker manifest annotate --variant v5 $DOCKER_REPO:latest $DOCKER_REPO:arm32v5
        docker manifest push $DOCKER_REPO:latest
# vim: set sw=2 ts=2 sts=2:
