name: build

on:
  push:
    paths-ignore:
    - 'support/*'
    - '.github/workflows/rustimg.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      RUST_TEST_THREADS: 1
    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive --depth 1

    - name: Install rust nightly
      run: rustup install nightly

    - name: Install grcov
      run: |
        mkdir $HOME/grcov
        curl -SsL "$GRCOV_URL" | tar -jxf - -C $HOME/grcov
        chmod +x $HOME/grcov/grcov
        echo "::add-path::$HOME/grcov"
      env:
        GRCOV_URL: 'https://github.com/mozilla/grcov/releases/download/v0.5.12/grcov-linux-x86_64.tar.bz2'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends libudev-dev libinput-dev llvm libgoogle-perftools-dev

    - name: Check format
      run: cargo fmt -- --check

    - name: Build
      run: cargo build --verbose --release

    - name: Run grcov
      run: |
        cargo +nightly build
        cargo +nightly test
        grcov ./target/debug -s . -t lcov --llvm --branch --ignore-not-existing -o lcov.info
      env:
        CARGO_INCREMENTAL: "0"
        RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
        RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'

    - uses: codecov/codecov-action@v1
      with:
        file: ./lcov.info

  build-image:
    runs-on: ubuntu-latest
    needs: check
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        arch:
        - amd64
        - arm32v5
        - arm32v7
    env:
      DOCKER_REPO: yskszk63/btknmle

    steps:
    - uses: actions/checkout@v2

    # work around for `Value too large for defined data type;`
    - name: Setup btrfs volume driver
      run: |
        sudo systemctl stop docker.service
        sudo fallocate -l10GB /mnt/docker.img
        sudo mkfs.btrfs /mnt/docker.img
        sudo mount -t btrfs /mnt/docker.img /var/lib/docker
        echo '{"storage-driver":"btrfs"}' | sudo tee /etc/docker/daemon.json > /dev/null
        sudo systemctl start docker.service

    - name: Setup binfmt
      run: |
        docker run --rm --privileged "$BINFMT_IMAGE"
      env:
        BINFMT_IMAGE: 'docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64'

    - name: Login Doker
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      env:
        DOCKER_USERNAME: yskszk63
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push
      run: |
        case "${{ matrix.arch }}" in
          "amd64")
            TARGETPLATFORM=linux/amd64
            ;;
          "arm32v7")
            TARGETPLATFORM=linux/arm/v7
            ;;
          "arm32v5")
            TARGETPLATFORM=linux/arm/v5
            ;;
        esac
        docker build \
          -t $DOCKER_REPO:$TARGETARCH \
          --build-arg TARGETPLATFORM=${TARGETPLATFORM} \
          .
        docker push $DOCKER_REPO:$TARGETARCH
      env:
        TARGETARCH: ${{ matrix.arch }}

    #- name: Build and push with tag
    #  if: startsWith(github.ref, 'refs/tags/')
    #  run: |
    #    TAG=${GITHUB_REF##*/}
    #    docker buildx build --platform "$PLATFORM" --push -t $DOCKER_REPO:$TAG .

  push-manifest:
    runs-on: ubuntu-latest
    needs: build-image
    if: github.ref == 'refs/heads/master'
    env:
      DOCKER_REPO: yskszk63/btknmle
      DOCKER_CLI_EXPERIMENTAL: enabled

    steps:
    - name: Login Doker
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      env:
        DOCKER_USERNAME: yskszk63
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

    - name: Create manifest
      run: |
        docker manifest create $DOCKER_REPO:latest \
          $DOCKER_REPO:amd64 \
          $DOCKER_REPO:arm32v7 \
          $DOCKER_REPO:arm32v5
        docker manifest annotate --variant v7 $DOCKER_REPO:latest $DOCKER_REPO:arm32v7
        docker manifest annotate --variant v5 $DOCKER_REPO:latest $DOCKER_REPO:arm32v5
        docker manifest push $DOCKER_REPO:latest
# vim: set sw=2 ts=2 sts=2:
