name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: rustup update
    - run: sudo apt update && sudo apt install -y libudev-dev libinput-dev
    - name: Check format
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/cache@v1
      with:
        path: ~/.cargo-sccache
        key: ${{ runner.os }}-cargo-sccache-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-sccache-
          ${{ runner.os }}-
    - run: |
        mkdir -p ~/.cargo-sccache
        docker run --name redis -d -v ~/.cargo-sccache:/data redis
        docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
        docker build -f build/Dockerfile.armv6 -t yskszk63/btknmle:armv6 .
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push yskszk63/btknmle:armv6
      env:
        DOCKER_USERNAME: yskszk63
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
