name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - run: rustup update

    - run: sudo apt update && sudo apt install -y libudev-dev libinput-dev

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
