name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - run: rustup update

    - run: sudo apt update && sudo apt install -y libudev-dev libinput-dev

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: sudo -E capsh --caps="cap_setpcap,cap_setuid,cap_setgid+ep cap_net_admin+ip" --keep=1 --user=$USER --addamb=cap_net_admin -- -c 'cargo test'
